#!/bin/sh

export LC_ALL=C LANGUAGE=C LANG=C
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

mount -t proc - /proc
mount / -o remount,rw

# format customer and data partition
for i in mmcblk1p5 mmcblk1p6 mmcblk1p7; do
	[ -b /dev/$i ] && mkfs.ext4 -F -F /dev/$i
done

mv /sbin/init.orig /sbin/init
exec /sbin/init
