#!/bin/sh

NORMALDIR="$1"
EARLYDIR="$2"
LATEDIR="$3"

ACTIVESLOT="$(sed 's/.*rauc\.slot=\([AB]\).*/\1/' /proc/cmdline)"

if [ "$ACTIVESLOT" = "A" ]; then
	cat <<-EOF > "$NORMALDIR/opt.mount"
	[Unit]
	Description=Customer Application File System (A)
	
	[Mount]
	What=/dev/mmcblk0p6
	Where=/opt
	EOF
else
	cat <<-EOF > "$NORMALDIR/opt.mount"
	[Unit]
	Description=Customer Application File System (B)
	
	[Mount]
	What=/dev/mmcblk0p7
	Where=/opt
	EOF
fi

mkdir -p "$NORMALDIR/sysinit.target.wants"
ln -s ../opt.mount "$NORMALDIR/sysinit.target.wants"
