#!/bin/sh

ACTION="$1"
MOUNTPOINT="$2"

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if [ "$ACTION" = "add" ]; then
	mkdir -p "/srv/rauc"

	CANDIDATES="$(find "$MOUNTPOINT" -name *.image)"
	if [ -n "$CANDIDATES" ]; then
		for x in $CANDIDATES; do
			BASENAME="$(basename $x .image)"
			BUNDLE="/srv/rauc/${BASENAME}.raucb"

			cp "$x" "$BUNDLE"

			echo "Would try to update with $BUNDLE" | logger
		done
	fi
fi
