#!/bin/sh

export LC_ALL=C LANGUAGE=C LANG=C
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# The data partition offset must be equal to the value from gen_emmc_3x_ext4.sh

cat <<EOF | fdisk /dev/mmcblk0
p
d
3
n
p
3
4218880

p
w
EOF
