#!/bin/sh
#
# This script copies some configuration file from current running system
# to the updated partition (new system).
#

SLOT_CLASS="$1"
SLOT_MOUNT_POINT="$2"
BUNDLE_MOUNT_POINT="$3"

if [ "$SLOT_CLASS" = "rootfs" ]; then
	( xargs tar -c --ignore-failed-read -C / ) <<-EOF | tar -x -C "$SLOT_MOUNT_POINT"
	/etc/hostname
	/etc/hosts
	/etc/machine-id
	/etc/network/interfaces
	/etc/ssh/ssh_host_ecdsa_key
	/etc/ssh/ssh_host_ecdsa_key.pub
	/etc/ssh/ssh_host_ed25519_key
	/etc/ssh/ssh_host_ed25519_key.pub
	/etc/ssh/ssh_host_rsa_key
	/etc/ssh/ssh_host_rsa_key.pub
	/root/.ssh
	/etc/rc.once.d/.done
	EOF

	# copy /etc/resolv.conf only if it is a plain file and not a link
	if [ -f /etc/resolv.conf -a ! -L /etc/resolv.conf ]; then
		rm -f "$SLOT_MOUNT_POINT/etc/resolv.conf"
		cat /etc/resolv.conf > "$SLOT_MOUNT_POINT/etc/resolv.conf"
	fi
fi
