#!/bin/sh
#
#  Copyright (c) 2013 I2SE GmbH
#

if [ $# -ne 3 ]; then
        echo "Usage: $0 INTERFACE OUI OTPREGISTER"
        exit 1
fi

oui="$2"
otpfile="/sys/fsl_otp/$3"

if [ "${#oui}" != "8" ]; then
        echo "Usage: $0 INTERFACE OUI OTPREGISTER"
        exit 1
fi

if [ ! -e "$otpfile" ]; then
        echo "File doesn't exists: $otpfile"
        exit 1
fi

val=`head "$otpfile"`
val=`printf "%08X" $((val))`
byte2=`echo $val | cut -b 3-4`
byte3=`echo $val | cut -b 5-6`
byte4=`echo $val | cut -b 7-8` 

/sbin/ifconfig "$1" hw ether "${oui}:${byte2}:${byte3}:${byte4}"

