#!/bin/sh

export LC_ALL=C LANGUAGE=C LANG=C
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

mount -t proc - /proc
mount / -o remount,rw

if [ -x /sbin/adjust-root-partition ]; then
	adjust-root-partition
	touch /resizefs
	rm -f /sbin/adjust-root-partition
	sync
	reboot -f
	while true; do
		:
	done
fi

if [ -e /resizefs ]; then
	resize2fs /dev/mmcblk0p2
	rm -f /resizefs
fi

mv /sbin/init.orig /sbin/init
exec /sbin/init
